### ISSUE TITLE
!when crashing

### ISSUE THREAD

**Issue by eastein** [eastein/dudemon#25]
[14 14:06:08] <+Toba> !when 1
[14 14:06:08] < schedmon> You're raising exceptions, toba. Don't worry, I still like you.

**Comment by eastein** [comment]
Traceback (most recent call last):
  File "./dudemon", line 194, in handle
    return dudeutils.when(self.state, now, count=n)
  File "/home/eastein/git/dudemon/dudeutils.py", line 88, in when
    ev = find_events()
  File "/home/eastein/git/dudemon/dudeutils.py", line 79, in find_events
    ets = st[k]
KeyError: 's'

**Comment by eastein** [comment]
This is breakage due to MAC based pamela_probe integration.

**Comment by eastein** [comment]
This is still happening, I should fix this.

**Comment by eastein** [comment]
Fixed.
